name: kalshi
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - black
  - ipykernel
  - matplotlib
  - mypy
  - pandas
  - pandas-stubs
  - pip
  - pytest
  - anaconda::jupyter
  - ca-certificates
  - certifi
  - openssl
  - scipy
  - numpy
  - xarray
  - cfgrib
  - urlpath
  - cachetools
  - tqdm
